# Build script to embed PNG icons as Base64 into JS file
# This ensures HACS downloads everything in a single file

$pngFiles = Get-ChildItem -Path "." -Filter "*.png" | Sort-Object Name

if ($pngFiles.Count -eq 0) {
    Write-Host "No PNG files found!"
    exit 1
}

Write-Host "Found $($pngFiles.Count) PNG files"

# Read the main JS file
$jsFile = "pocasimeteo-card.js"
if (!(Test-Path $jsFile)) {
    Write-Host "Error: $jsFile not found!"
    exit 1
}

$jsContent = Get-Content $jsFile -Raw -Encoding UTF8

# Generate Base64 data object
$base64Data = @()
$totalSize = 0

foreach ($pngFile in $pngFiles) {
    $pngBytes = [System.IO.File]::ReadAllBytes($pngFile.FullName)
    $b64String = [Convert]::ToBase64String($pngBytes)
    $iconName = $pngFile.BaseName
    $base64Data += "    `"$iconName`": `"data:image/png;base64,$b64String`""
    $totalSize += $pngBytes.Length
}

Write-Host "Total PNG size: $([math]::Round($totalSize / 1KB, 1)) KB"
Write-Host "Base64 size: $([math]::Round($totalSize * 1.37 / 1KB, 1)) KB (estimated)"

# Create the embedded icons object
$iconsObject = "  const EMBEDDED_ICONS = {`r`n" + ($base64Data -join ",`r`n") + "`r`n  };`r`n"

# Find the insertion point - right after "(() => {"
$pattern = '\(\(\) => \{'
if ($jsContent -match $pattern) {
    $insertIndex = $matches[0].Length + $jsContent.IndexOf($matches[0])

    # Split content
    $before = $jsContent.Substring(0, $insertIndex)
    $after = $jsContent.Substring($insertIndex)

    # Insert embedded icons with proper comment
    $newContent = $before + "`r`n  // Embedded Base64 icons (auto-generated by build_embedded.ps1)`r`n" + $iconsObject + $after

    Write-Host "SUCCESS: Found insertion point and embedded icons"
} else {
    Write-Host "ERROR: Could not find '(() => {' pattern in JS file!"
    exit 1
}

# Write the modified JS file with UTF-8 without BOM
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
[System.IO.File]::WriteAllText($jsFile, $newContent, $Utf8NoBomEncoding)

Write-Host "SUCCESS: Embedded $($pngFiles.Count) icons into $jsFile"
Write-Host "File size: $([math]::Round(($newContent.Length) / 1KB, 1)) KB"
