#!/usr/bin/env python3
"""
Build script to embed PNG icons as Base64 into JS file.
This ensures HACS downloads everything in a single file.
"""
import base64
import os
from pathlib import Path

def main():
    # Get all PNG files in current directory
    png_files = sorted(Path('.').glob('*.png'))

    if not png_files:
        print("No PNG files found!")
        return

    print(f"Found {len(png_files)} PNG files")

    # Read the main JS file
    js_file = Path('pocasimeteo-card.js')
    if not js_file.exists():
        print(f"Error: {js_file} not found!")
        return

    js_content = js_file.read_text(encoding='utf-8')

    # Generate Base64 data object
    base64_data = []
    total_size = 0

    for png_file in png_files:
        with open(png_file, 'rb') as f:
            png_bytes = f.read()
            b64_string = base64.b64encode(png_bytes).decode('ascii')
            base64_data.append(f'    "{png_file.stem}": "data:image/png;base64,{b64_string}"')
            total_size += len(png_bytes)

    print(f"Total PNG size: {total_size / 1024:.1f} KB")
    print(f"Base64 size: {total_size * 1.37 / 1024:.1f} KB (estimated)")

    # Create the embedded icons object
    icons_object = "  const EMBEDDED_ICONS = {\n" + ",\n".join(base64_data) + "\n  };\n"

    # Find the ICON_BASE_PATH definition and replace it
    # We'll add EMBEDDED_ICONS right after the IIFE opening
    replacement = f"""(() => {{
  // Embedded Base64 icons (auto-generated by build_embedded.py)
{icons_object}
  // Detekuj base path IHNED při načtení modulu (kdy document.currentScript ještě existuje)
  // Ikony jsou nyní přímo v dist/ (ne v dist/icons/) pro kompatibilitu s Cloudflare tunnel
  const ICON_BASE_PATH = (() => {{"""

    # Replace the opening
    js_content = js_content.replace(
        """(() => {
  // Detekuj base path IHNED při načtení modulu (kdy document.currentScript ještě existuje)
  // Ikony jsou nyní přímo v dist/ (ne v dist/icons/) pro kompatibilitu s Cloudflare tunnel
  const ICON_BASE_PATH = (() => {""",
        replacement
    )

    # Write the modified JS file
    output_file = Path('pocasimeteo-card.js')
    output_file.write_text(js_content, encoding='utf-8')

    print(f"✓ Successfully embedded {len(png_files)} icons into {output_file}")
    print(f"✓ File size: {len(js_content) / 1024:.1f} KB")

if __name__ == '__main__':
    main()
