# Build script to create dist version with embedded Base64 icons
# Output goes to dist/ folder for HACS

$pngFiles = Get-ChildItem -Path "." -Filter "*.png" | Sort-Object Name

if ($pngFiles.Count -eq 0) {
    Write-Host "No PNG files found!"
    exit 1
}

Write-Host "Found $($pngFiles.Count) PNG files"

# Read the SOURCE JS file from src/
$jsFile = "src\pocasimeteo-card.js"
if (!(Test-Path $jsFile)) {
    Write-Host "Error: $jsFile not found!"
    exit 1
}

$jsContent = Get-Content $jsFile -Raw -Encoding UTF8

# Replace window.POCASIMETEO_EMBEDDED_ICONS with local EMBEDDED_ICONS
$jsContent = $jsContent -replace "typeof window\.POCASIMETEO_EMBEDDED_ICONS !== 'undefined' && window\.POCASIMETEO_EMBEDDED_ICONS\[iconKey\]", "typeof EMBEDDED_ICONS !== 'undefined' && EMBEDDED_ICONS[iconKey]"
$jsContent = $jsContent -replace "window\.POCASIMETEO_EMBEDDED_ICONS\[iconKey\]", "EMBEDDED_ICONS[iconKey]"

# Generate Base64 data object
$base64Data = @()
$totalSize = 0

foreach ($pngFile in $pngFiles) {
    $pngBytes = [System.IO.File]::ReadAllBytes($pngFile.FullName)
    $b64String = [Convert]::ToBase64String($pngBytes)
    $iconName = $pngFile.BaseName
    $base64Data += "    `"$iconName`": `"data:image/png;base64,$b64String`""
    $totalSize += $pngBytes.Length
}

Write-Host "Total PNG size: $([math]::Round($totalSize / 1KB, 1)) KB"
Write-Host "Base64 size: $([math]::Round($totalSize * 1.37 / 1KB, 1)) KB (estimated)"

# Create the embedded icons object
$iconsObject = "  const EMBEDDED_ICONS = {`r`n" + ($base64Data -join ",`r`n") + "`r`n  };`r`n"

# Find the insertion point (right after the opening IIFE)
$pattern = "(?s)\(\(\) => \{[\r\n]+"
if ($jsContent -match $pattern) {
    # Create replacement with embedded icons
    $replacement = "(() => {`r`n  // Embedded Base64 icons (auto-generated by build_dist.ps1)`r`n" + $iconsObject + "`r`n"

    $jsContent = $jsContent -replace $pattern, $replacement

    Write-Host "SUCCESS: Embedded icons into JS content"
} else {
    Write-Host "ERROR: Could not find insertion pattern in JS file!"
    Write-Host "Looking for pattern: (() => {"
    exit 1
}

# Create dist directory if it doesn't exist
$distDir = "dist"
if (!(Test-Path $distDir)) {
    New-Item -ItemType Directory -Path $distDir | Out-Null
}

# Write to dist folder with UTF-8 without BOM
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
$outputFile = Join-Path $distDir "pocasimeteo-card.js"
[System.IO.File]::WriteAllText($outputFile, $jsContent, $Utf8NoBomEncoding)

Write-Host "SUCCESS: Created $outputFile with $($pngFiles.Count) embedded icons"
Write-Host "File size: $([math]::Round(($jsContent.Length) / 1KB, 1)) KB"
