# Build script to embed PNG icons as Base64 into JS file
# This ensures HACS downloads everything in a single file

$pngFiles = Get-ChildItem -Path "." -Filter "*.png" | Sort-Object Name

if ($pngFiles.Count -eq 0) {
    Write-Host "No PNG files found!"
    exit 1
}

Write-Host "Found $($pngFiles.Count) PNG files"

# Read the main JS file
$jsFile = "pocasimeteo-card.js"
if (!(Test-Path $jsFile)) {
    Write-Host "Error: $jsFile not found!"
    exit 1
}

$jsContent = Get-Content $jsFile -Raw -Encoding UTF8

# Generate Base64 data object
$base64Data = @()
$totalSize = 0

foreach ($pngFile in $pngFiles) {
    $pngBytes = [System.IO.File]::ReadAllBytes($pngFile.FullName)
    $b64String = [Convert]::ToBase64String($pngBytes)
    $iconName = $pngFile.BaseName
    $base64Data += "    `"$iconName`": `"data:image/png;base64,$b64String`""
    $totalSize += $pngBytes.Length
}

Write-Host "Total PNG size: $([math]::Round($totalSize / 1KB, 1)) KB"
Write-Host "Base64 size: $([math]::Round($totalSize * 1.37 / 1KB, 1)) KB (estimated)"

# Create the embedded icons object
$iconsObject = "  const EMBEDDED_ICONS = {`n" + ($base64Data -join ",`n") + "`n  };`n"

# Find and replace the opening
$oldOpening = @"
(() => {
  // Detekuj base path IHNED při načtení modulu (kdy document.currentScript ještě existuje)
  // Ikony jsou nyní přímo v dist/ (ne v dist/icons/) pro kompatibilitu s Cloudflare tunnel
  const ICON_BASE_PATH = (() => {
"@

$newOpening = @"
(() => {
  // Embedded Base64 icons (auto-generated by build_embedded.ps1)
$iconsObject
  // Detekuj base path IHNED při načtení modulu (kdy document.currentScript ještě existuje)
  // Ikony jsou nyní přímo v dist/ (ne v dist/icons/) pro kompatibilitu s Cloudflare tunnel
  const ICON_BASE_PATH = (() => {
"@

$jsContent = $jsContent.Replace($oldOpening, $newOpening)

# Write the modified JS file
Set-Content -Path $jsFile -Value $jsContent -Encoding UTF8 -NoNewline

Write-Host "✓ Successfully embedded $($pngFiles.Count) icons into $jsFile"
Write-Host "✓ File size: $([math]::Round(($jsContent.Length) / 1KB, 1)) KB"
